#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["dev_v2/dev_v1.csproj", "dev_v2/"]
RUN dotnet restore "dev_v2/dev_v2.csproj"
COPY . .
WORKDIR "/src/dev_v2"
RUN dotnet build "dev_v2.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "dev_v2.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "dev_v2.dll"]
